### ISSUE TITLE
.unknown audio files (header .afs and .idx) [audio_eng_5b69b0ee archive]

### ISSUE THREAD

**Issue by makc-ar** [derplayer/ShenmueHDTools#1]
Hi **derplayer** How about export for header?

**Comment by derplayer** [comment]
Hey, i'll add audio support later i guess, but for now normal File/Texturefile replacing is my priority

**Comment by makc-ar** [comment]
These https://www35.zippyshare.com/v/W7vUMCgG/file.html textures can be extracted with a DDS header and imported without header?

**Comment by derplayer** [comment]
sure, maybe shenmue can even work with a imported header for those files it is pretty robust for file edits so it could work
