### ISSUE TITLE
Deploy Release 1.2

### ISSUE THREAD

**Issue by philyeahz** [derplayer/ShenmueHDTools#15]

**Comment by derplayer** [comment]
Okay, will test stuff out and update the updater stuff when everyting is ok.  We also need to polish the FAQ and new picture/s?

**Comment by derplayer** [comment]
Notes

* Map filesnames to TAD - dosen't map on extracted unknowns (when without database)
* Compress resources
* Embedd frameworks in resources
* Generate a ready-to-go "database.bin" database, that is used at first start (with SM1&2 with all version files from my steam!)
* When description is too long it "..." the text away. Multiline Descriptions?
* Map filenames dosent show a loading dialog (takes 10-20 secs, main window hangs)
* Stop button for wuu fetch? Application only killable over taskmgr
* database.bin dosent work without debugger?

**Comment by philyeahz** [comment]
Everything done except:
3. Generate a ready-to-go "database.bin" database, that is used at first start (with SM1&2 with all version files from my steam!)
4. When description is too long it "..." the text away. Multiline Descriptions?

**Comment by derplayer** [comment]
Number 4 is unnecessary (we talked about it)

I also need to add the missing Japanese SM2 DC Index files.

**Comment by philyeahz** [comment]
🎉
