### ISSUE TITLE
Test new codebase before release

### ISSUE THREAD

**Issue by derplayer** [derplayer/ShenmueHDTools#16]

**Comment by derplayer** [comment]
DataTables caused hard lags. Fixed.

**Comment by philyeahz** [comment]
Added automatic +5 years when packing TAC/TAD. Later the mod manager will write those timestamps with user defined priority in mind.

**Comment by maciekweryszko** [comment]
Major bugs are ridden off. Final test of export with game can now be done. Then this can be closed!

**Comment by derplayer** [comment]
Major bugs are ridden off. Final test of export with game can now be done. Then this can be closed!

**Comment by derplayer** [comment]
Everything works now.
