### ISSUE TITLE
Add Header to Headerless files

### ISSUE THREAD

**Issue by derplayer** [derplayer/ShenmueHDTools#18]
Analyse file and create a valid header (for smoother modding workflow, dds files in common)
After 1.2...

**Comment by derplayer** [comment]
Note: Needs to test it out if it is possible (the game doesn't crash & loads the header file successfully)

**Comment by philyeahz** [comment]
DDS files (DXT1, DXT3) sometimes with, and sometimes without mipmaps...
Should have the same size and mipmap count as the source texture.

**Comment by philyeahz** [comment]
Seems useless to implement something that adds headers when importing. (also impossible without knowing source image)
