### ISSUE TITLE
Modtools implementations (Future)

### ISSUE THREAD

**Issue by derplayer** [derplayer/ShenmueHDTools#19]
Worksflow:
User selects a file and clicks edit file ->  software selects automaticly a modtool (or show modtools to selection?)

**Comment by derplayer** [comment]
https://sourceforge.net/p/shenmuesubs/code/HEAD/tree/

PKF Texture Editor (IPAC Browser Extension)
https://www.shenmuedojo.com/forum/index.php?threads/mod-tool-request-pkf-texture-editor-ipac-browser-update.568/

Other
https://www.shenmuedojo.com/forum/index.php?threads/shenmue-i-ii-mod-database.464/

**Comment by derplayer** [comment]
Priority
IPAC Browser
SPR Utils
Models Textures Editor (?)
IDX Creator / AFS Utils

Custom:
Texture Editor (header, type logic, etc)
Model Converter (MT5,MT7)

Needs RW brecause is different implemented in SHD
Subtitles Editor / Cinematics Subtitles Editor
Font Utility
MAP Editor (Does it even exist? in parts https://sourceforge.net/p/shenmuesubs/code/HEAD/tree/Internal/MapInfo/)
Free Quest Subtitles Editor(?)

**Comment by philyeahz** [comment]
Closed because creating all possible mod tools for 1.3.
