### ISSUE TITLE
Database extension - File Description

### ISSUE THREAD

**Issue by derplayer** [derplayer/ShenmueHDTools#31]
There are some item descriptions available in internet. You could also add your own notes.
For more look: wiki page

**Comment by philyeahz** [comment]
Descriptions should be searched for in runtime because the TAD component has no interest in this metadata. If you really want to save these descriptions than i would recommend creating an project file format.

**Comment by derplayer** [comment]
But we have already the shdcahe/cache file, lets just put the description in there. Runtime wouldn't allow adding own strings/notes in description.

**Comment by derplayer** [comment]
The descriptions in wiki are for this field. Im still collecting. They need to be referenced at cache generation, so no dont close for now.
