### ISSUE TITLE
Image Preview (PVR, DDS)

### ISSUE THREAD

**Issue by philyeahz** [derplayer/ShenmueHDTools#34]
The image formats DDS and PVR need to be displayed and converted from/to bitmap.

**Comment by philyeahz** [comment]
PVR, DDS to bitmap conversion and image preview done.

**Comment by derplayer** [comment]
Do we wanna merge the Deep Learning stuff in Image Preview into main branch?

**Comment by philyeahz** [comment]
No.
Do an extra tool in the Tools menu for batch converting/scaling textures

**Comment by philyeahz** [comment]
Reading of all needed formats is already inside SDK. Only HDTools needs to implement it.

**Comment by derplayer** [comment]
DDS and PVR previews are already implemented with latest commit.
PVR has also Deep learning upscale preview elements. This needs to be done also for DDS stuff (with propper mipmaps upscaling)
